#!/usr/bin/env sh

set -e

rootdir="$(pwd)"
ZIG_VERSION="$("$rootdir/out/host/bin/zig" version)"
echo "zig_version='$ZIG_VERSION'"

target="x86_64-windows-gnu"
target_and_cpu=$target-baseline

TARBALL_BASENAME="zig+llvm+lld+clang-$target-$ZIG_VERSION"
DEVKIT_PARENT_DIR="$rootdir/out/windows-devkit"
devkit="$DEVKIT_PARENT_DIR/$TARBALL_BASENAME"

rm -rf "$devkit" "$devkit.zip"
mkdir -p "$devkit"

echo "copying devkit files..."
cp -R "$rootdir/out/$target_and_cpu/"* "$rootdir/out/zig-$target_and_cpu/"* "$devkit/"

echo "renaming libX.a to X.lib"
for f in $(find "$devkit/lib/"lib*.a); do
    dirname="$(dirname "$f")"
    basename="$(basename "$f")"
    new_name="$dirname/$(echo "$basename" | sed 's/^lib//' | sed 's/a$/lib/')"
    mv "$f" "$new_name"
done

echo "removing ld exes..."
rm "$devkit/bin/"*ld*.exe

cd "$DEVKIT_PARENT_DIR"
DEV_KIT_ZIP="$TARBALL_BASENAME.zip"
7z a "$DEV_KIT_ZIP" "$TARBALL_BASENAME/"

SHASUM=$(sha256sum "$DEV_KIT_ZIP")
BYTE_COUNT=$(wc -c "$DEV_KIT_ZIP")

s3cmd put -P \
  --add-header="cache-control: public, max-age=31536000, immutable" \
  "$DEV_KIT_ZIP" s3://ziglang.org/deps/

cd $rootdir
echo "URL: https://ziglang.org/deps/$DEV_KIT_ZIP"
echo "sha256: $SHASUM"
echo "size: $BYTE_COUNT bytes"
