#!/bin/sh

WWWSRC="$HOME/dev/www.ziglang.org"
ZIGSRC="$HOME/Downloads/zig"
TMPDIR="$HOME/tmp"
OLDVER="0.8.0"
NEWVER="0.9.0"

set -e

mkdir "$WWWSRC/src/download/$NEWVER"
mkdir "$WWWSRC/content/download/$NEWVER"

cp "$WWWSRC/src/download/$OLDVER/release-notes.html" \
   "$WWWSRC/src/download/$NEWVER/release-notes.html"

DOCGEN="$(find "$ZIGSRC/zig-cache" -name docgen | head -n1)"
cp "$DOCGEN" "$TMPDIR/"

echo "command to compile the release notes:"
echo "$TMPDIR/docgen zig $WWWSRC/src/download/$NEWVER/release-notes.html $WWWSRC/content/download/$NEWVER/release-notes.html"

