#!/bin/sh

set -e

BOOTSTRAP_REPO="$1"
LLVM_REPO="$2"

cd "$BOOTSTRAP_REPO"
rm -rf clang lld llvm

cp -r "$LLVM_REPO/llvm/" ./
cp -r "$LLVM_REPO/clang/" ./
cp -r "$LLVM_REPO/lld/" ./
rm -rf \
  {llvm,lld,clang}/build-*/ \
  clang/test/ \
  clang/tools/scan-view/ \
  lld/.clang-tidy \
  lld/test/ \
  llvm/test/ \
  llvm/utils/{benchmark,docker,gn,lit,vim,vscode,git}/ \
  llvm/utils/pipeline.py \
  llvm/utils/llvm-mca-compare.py \
  llvm/utils/rsp_bisect.py \
  llvm/utils/rsp_bisect_test/ \
  llvm/utils/reduce_pipeline.py \
  llvm/utils/reduce_pipeline_test/ \
  llvm/utils/release/ \
  clang/docs/ \
  llvm/docs/ \
  lld/docs/ \
  llvm/bindings/ \
  llvm/examples/ \
  clang/examples/

echo "Inspect git status, then do the following commands:"
echo 'git commit -a -m "update LLVM sources to XYZ"'
echo "next, look at the commits directly after the previous update commit and apply relevant patches"
