#!/bin/sh

set -eu

BOOTSTRAP_REPO="$1"
ZIG_REPO="$2"
ZIG_VERSION="$3"

cd "$BOOTSTRAP_REPO"
rm -rf zig/

git -C "$ZIG_REPO" archive --format=tar --prefix=zig/ HEAD | tar -x
rm -rf \
  "zig/.github" \
  "zig/.gitignore" \
  "zig/.gitattributes" \
  "zig/.git" \
  "zig/.mailmap" \
  "zig/ci"

sed -i "/^ZIG_VERSION=\".*\"\$/c\\ZIG_VERSION=\"$ZIG_VERSION\"" build
sed -i "/^set ZIG_VERSION=\".*\"\r\$/c\\set ZIG_VERSION=\"$ZIG_VERSION\"\r" build.bat
sed -i "/^ \* zig /c\\ * zig $ZIG_VERSION" README.md
sed -i "/^        const char \*zig_version = \"/c\\        const char *zig_version = \"$ZIG_VERSION\";" zig/bootstrap.c

git add -A
git commit -m "update zig sources to $ZIG_VERSION"

echo "This script made a commit to zig-bootstrap on your behalf; don't forget to inspect it before pushing!"
