#!/bin/sh

set -e

BOOTSTRAP_REPO="$1"
LLVM_REPO="$2"

cd "$BOOTSTRAP_REPO"
rm -rf clang lld llvm

cp -r "$LLVM_REPO/llvm/" ./
cp -r "$LLVM_REPO/clang/" ./
cp -r "$LLVM_REPO/lld/" ./
rm -rf \
  {llvm,lld,clang}/build-*/ \
  clang/test/ \
  clang/tools/scan-view/ \
  lld/.clang-tidy \
  lld/test/ \
  llvm/test/ \
  llvm/utils/{benchmark,docker,gn,lit,vim,vscode,git}/ \
  llvm/utils/pipeline.py \
  llvm/utils/llvm-mca-compare.py \
  llvm/utils/rsp_bisect.py \
  llvm/utils/rsp_bisect_test/ \
  llvm/utils/reduce_pipeline.py \
  llvm/utils/reduce_pipeline_test/ \
  llvm/utils/release/ \
  clang/docs/ \
  llvm/docs/ \
  lld/docs/ \
  llvm/bindings/ \
  llvm/examples/ \
  clang/examples/

echo "Inspect git status, then do the following commands:"
echo 'git commit -a -m "update LLVM sources to XYZ"'
echo "git cherry-pick 52618cb7243119ab1b4228f7c809bbfe35a725ba"
echo "git cherry-pick bf6e8cf1e4f47171304524b14614d820b8c73bbd"
echo "merge one of those two commits with f53db28e8cdf5661e3980ee50e745b88e452a280"
